node
{
stage ( 'SCM CHECKOUT')
{
git 'https://github.com/kusupudiswamy/maven-hello-world/tree/master/my-app'
}
  stage ('compile-package'){
    def mavenhome=tool name: 'maven', type: 'maven'
    sh "${mavenhome}/bin/mvn package"

  }

}
